#!/usr/bin/env python3
#
#  Compares two Tecplot files generated by horses2plt with the same mesh,
#  options and variables. For every variable, the maximum absolute difference
#  is scaled with the maximum absolute value of that variable in the reference.
#  Variable names are compared ignoring case.
#
#  Usage: ./compare_tec.py REFERENCE.tec RESULT.tec [TOLERANCE]
#
import math
import sys

def load(fileName):
    variables, rows = None, []
    with open(fileName) as f:
        for line in f:
            if line.startswith("VARIABLES"):
                variables = [v.strip().strip('"') for v in line.split("=", 1)[1].split(",")]
            elif line.startswith(("TITLE", "ZONE")):
                continue
            else:
                values = line.split()
                if values:
                    rows.append([float(v) for v in values])
    return variables, rows

refFile, resFile = sys.argv[1], sys.argv[2]
tol = float(sys.argv[3]) if len(sys.argv) > 3 else 1.0e-10

refVars, ref = load(refFile)
resVars, res = load(resFile)

if [v.lower() for v in refVars] != [v.lower() for v in resVars]:
    sys.exit(f"FAILED: different variables\n  {refVars}\n  {resVars}")
if len(ref) != len(res) or any(len(a) != len(b) for a, b in zip(ref, res)):
    sys.exit(f"FAILED: different number of points ({len(ref)} vs {len(res)})")

for fileName, rows in ((refFile, ref), (resFile, res)):
    if not all(math.isfinite(v) for row in rows for v in row):
        sys.exit(f"FAILED: {fileName} contains NaN or infinite values")

failed = False
for i, var in enumerate(refVars):
    scale = max(abs(r[i]) for r in ref)
    diff = max(abs(a[i] - b[i]) for a, b in zip(ref, res))
    relDiff = diff / scale if scale > 0.0 else diff
    ok = relDiff <= tol
    status = "OK" if ok else "FAILED"
    failed = failed or not ok
    print(f"{var:>10s}: max rel diff = {relDiff:.3e}  [{status}]")

if failed:
    sys.exit(f"FAILED: {resFile} differs from {refFile} (tolerance {tol:.1e})")
print(f"OK: {resFile} matches {refFile} (tolerance {tol:.1e}, {len(ref)} points)")
