#!/bin/bash
#
#  Checks a Tecplot file generated by horses2plt.
#
#  Usage: ./check_tec.sh FILE.tec [ZONE_TYPE] [VARIABLE ...]
#
#     ZONE_TYPE: BRICK (volume FE), QUADRILATERAL (surface FE), ORDERED (multizone)
#                or "-" to skip the check.
#     VARIABLE:  variable names that must appear in the VARIABLES header.
#                With a "+" prefix (e.g. +yplus), the variable must also be
#                strictly positive at every point (only for FE files, which
#                have a single fluid zone).
#
#  horses2plt may exit with code 0 even if the conversion was not performed,
#  so the output file itself is what gets validated here.
#
file=$1
zone=${2:--}
shift 2 2>/dev/null

fail() { echo "FAILED [$file]: $*"; exit 1; }

[ -s "$file" ] || fail "file does not exist or is empty"

head -1 "$file" | grep -q '^TITLE' || fail "missing TITLE header"
varLine=$(grep -m1 '^VARIABLES' "$file") || fail "missing VARIABLES header"
grep -q '^ZONE' "$file" || fail "no ZONE found"

case $zone in
   -) ;;
   ORDERED) grep -m1 '^ZONE' "$file" | grep -q 'I=' || fail "expected ordered (multizone) zones" ;;
   *) grep -m1 '^ZONE' "$file" | grep -q "ET=$zone" || fail "expected ZONE with ET=$zone" ;;
esac

for arg in "$@"; do
   var=${arg#+}
   echo "$varLine" | grep -q "\"$var\"" || fail "variable \"$var\" not found in: $varLine"
done

grep -qiE '(^|[^a-z])(nan|infinity)([^a-z]|$)' "$file" && fail "NaN/Infinity values found"

for arg in "$@"; do
   [ "${arg:0:1}" == "+" ] || continue
   var=${arg#+}
   # Column of the variable and number of columns of the point data
   col=$(echo "$varLine" | sed 's/^VARIABLES *= *//' | tr ',' '\n' | grep -nx "\"$var\"" | cut -d: -f1)
   ncols=$(echo "$varLine" | sed 's/^VARIABLES *= *//' | tr ',' '\n' | wc -l)
   result=$(awk -v c=$col -v n=$ncols '
      /^ZONE/ { zones++; next }
      zones == 1 && NF == n { np++; v = $c + 0; if (np == 1 || v < vmin) vmin = v; if (np == 1 || v > vmax) vmax = v }
      END { printf "%d %.6e %.6e", np, vmin, vmax }' "$file")
   read np vmin vmax <<< "$result"
   [ "$np" -gt 0 ] || fail "no point data found to check \"$var\""
   awk -v v=$vmin 'BEGIN { exit !(v > 0) }' || fail "\"$var\" is not strictly positive (min = $vmin, max = $vmax)"
   echo "   \"$var\": $np points, min = $vmin, max = $vmax"
done

echo "OK [$file]: $(grep -c '^ZONE' "$file") zone(s), $varLine"
